name: 'data_warehouse'
version: '1.0'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'data_warehouse'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  data_warehouse:
      incremental_strategy: "delete+insert"

seeds:
  data_warehouse:
    sales:
      schema: staging
      column_types:
        datetime: timestamp
    dim_user:
      schema: datamart
      column_types:
        load_date: date